-- Crear tabla de roles
CREATE TABLE rol (
    id_rol INTEGER PRIMARY KEY,
    tipo VARCHAR(50) NOT NULL
);

INSERT INTO rol (id_rol,tipo) 
VALUES (1,'administrador'), 
(2,'usuario');

-- Crear tabla de usuarios
CREATE TABLE usuario (
    id_usuario SERIAL PRIMARY KEY,
    nombre_completo VARCHAR(100) NOT NULL,
    "user" VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(100) NOT NULL,
    id_rol INTEGER REFERENCES rol(id_rol)
);


-- Crear tabla de traducciones sin creado_por ni fecha_creacion
CREATE TABLE traduccion (
    id_traduccion SERIAL PRIMARY KEY,
    espanol VARCHAR(100) NOT NULL,
    shuar VARCHAR(100) NOT NULL
);

-- Crear usuario administrador por defecto
INSERT INTO usuario (nombre_completo, "user", password, id_rol)
VALUES ('Josue Abad', 'josue', '123', 1),
('Arian Leon', 'arian', '456',1),
('Diego Dominguez', 'diego', '789',1),
('Wilmer Espinoza', 'wilmer','123',1),
('Sebastian Nasqui', 'sebastian','456',1),
('Renato Abad', 'renato', '789',2);

-- Ingreso de datos a la tabla traduccion
INSERT INTO traduccion (espanol, shuar)
VALUES 
  ('abuelo', 'apachich'),
  ('abuela', 'nukuchich'),
  ('madre', 'nukúr'),
  ('hijo', 'uchir'),
  ('hija', 'nawantur'),
  ('nieto/a', 'tirank'),
  ('cuñado', 'wajér'),
  ('cuñada', 'yuar'),
  ('primo', 'kaná umar'),
  ('prima', 'kaná kaér'),
  ('gallina', 'jurétam'),
  ('pollo', 'shiampach'),
  ('ganso', 'suich'),
  ('gallo', 'áyum'),
  ('pato', 'pátu'),
  ('patito', 'patúch'),
  ('cerdo', 'kük'),
  ('vaca', 'wadka núa'),
  ('toro', 'wadka aishmank'),
  ('gato', 'michík'),
  ('perro', 'yawā'),
  ('caballo', 'kawal'),
  ('cuy', 'kuwi'),
  ('conejo', 'sawa'),
  ('venado', 'jápa'),
  ('oso perezoso', 'uyush'),
  ('tigrillo', 'yantána'),
  ('tejón', 'kushi'),
  ('ratón', 'katíp'),
  ('puerco espín', 'kuru'),
  ('oso', 'chai'),
  ('tigre', 'uunt yawá'),
  ('loro', 'kavá'),
  ('pava', 'tuish'),
  ('perico', 'pirish'),
  ('papagayo', 'yampuna'),
  ('gorrión', 'pinchuchink'),
  ('perdiz', 'waa'),
  ('colibrí', 'jempe'),
  ('cuervo', 'shanashnia'),
  ('gavilán', 'pinchu'),
  ('trompetero', 'chìwia'),
  ('garza', 'imia'),
  ('tucan', 'tsukanka'),
  ('lechuza', 'ampush'),
  ('escopeta', 'akáru'),
  ('banco', 'kután'),
  ('canasta', 'chankin'),
  ('aventador', 'awajint'),
  ('machete', 'máchit'),
  ('hacha', 'jacha'),
  ('cobacha', 'dák'),
  ('escoba', 'japímiuk'),
  ('bodoquera', 'unip'),
  ('trono shuar', 'tálnk'),
  ('palo para chicha', 'tálnk'),
  ('coleóptero', 'sésenk'),
  ('mariposa', 'wámpishuk'),
  ('mosquito', 'tete'),
  ('comején', 'káma'),
  ('conga', 'yutuf'),
  ('zancudo', 'manchu'),
  ('grillo', 'manchi'),
  ('pulga', 'sunku'),
  ('mosca', 'kaáp'),
  ('foca', 'págap'),
  ('pez espada', 'tsurikap'),
  ('bagre blanco', 'adíkiap'),
  ('caracol', 'tsuntsu'),
  ('cangrejo', 'úrik'),
  ('corvina', 'kusθá'),
  ('caracha', 'shaacham'),
  ('delfín', 'wapú'),
  ('bagre', 'kumpá'),
  ('sapo', 'kuraip'),
  ('guanta', 'káshai'),
  ('ardilla', 'kunamp'),
  ('danta o tapir', 'pamá'),
  ('guatuza', 'káyuk'),
  ('armadillo', 'shushui'),
  ('sajino', 'paki'),
  ('mono nocturno', 'ujúkam'),
  ('chichico', 'tseepai'),
  ('oso hormiguero', 'manchúnk'),
  ('mono', 'washi'),
  ('mono chorongo', 'chuú'),
  ('zorro', 'kujáncham'),
  ('plátano', 'tsamá'),
  ('limón', 'yumúnk'),
  ('granadilla', 'múnchi'),
  ('caña', 'padf'),
  ('naranjilla', 'kukuch'),
  ('papaya', 'wapai'),
  ('naranja', 'naránk'),
  ('uva silvestre', 'shuinia'),
  ('piña', 'chiú'),
  ('achuar', 'achuar'),
  ('awá', 'awá'),
  ('tsa’chi', 'tsa’chi'),
  ('zápara', 'zápara'),
  ('cofán', 'cofán'),
  ('siona', 'siona'),
  ('secoya', 'secoya'),
  ('shuar', 'shuar'),
  ('kichwa', 'kichwa'),
  ('afro-americano', 'mukusa'),
  ('huao', 'huao'),
  ('mestizo', 'apach'),
  ('corona', 'tawásap'),
  ('cinta', 'sénta'),
  ('lanza', 'nánki'),
  ('adorno para hombros', 'awankem'),
  ('cinturón', 'shakáp'),
  ('vestido', 'tardeh'),
  ('aretes de tucán', 'tsukánka'),
  ('pulsera', 'patáke sénta'),
  ('camisa', 'pushi'),
  ('sombrero', 'crisénkrutai'),
  ('gorro', 'mukatsuermann'),
  ('medias', 'iklujmammave'),
  ('pantalón', 'piisumprak'),
  ('saco', 'trup-pushi'),
  ('bufanda', 'penuman'),
  ('poncho', 'tsuempruk'),
  ('bikini', 'piisumak'),
  ('zapato', 'sapát'),
  ('abrigo', 'tujuch'),
  ('vincha', 'inklumatai'),
  ('aretes', 'esékmatai'),
  ('cobija', 'esékmatai'),
  ('flauta', 'pinkiuf'),
  ('guitarra', 'kitiar'),
  ('tambor', 'tampúr'),
  ('violín', 'kaér'),
  ('arco de cuerda', 'tumánk'),
  ('plato', 'yukúní'),
  ('tazón', 'amámuk'),
  ('colador', 'tsátsa'),
  ('vasija para chicha', 'muits'),
  ('olla de barro', 'ichínkian'),
  ('peinilla', 'temásh'),
  ('jabón', 'sékemur'),
  ('espejo', 'ispik'),
  ('papel higiénico', 'utúkmiatai papi'),
  ('cepillo', 'nai-nijiatai'),
  ('perfume', 'kunkuín'),
  ('agua', 'entsa'),
  ('helicóptero', 'antach'),
  ('canoa', 'kánu'),
  ('carreta', 'muwa-ewekamin'),
  ('balsa', 'pápank'),
  ('carro', 'kumkuim'),
  ('avión', 'nánap'),
  ('pelota', 'sankûntici'),
  ('lápices de colores', 'yakûtai'),
  ('zumbambico', 'wésham'),
  ('rompecabezas', 'waditai'),
  ('carrito', 'kunkulmiach'),
  ('trompo', 'wea-wea'),
  ('sol', 'etsa'),
  ('luna', 'nantu'),
  ('lluvia', 'yúmi'),
  ('nube', 'yuránkim'),
  ('arco iris', 'tuntíák'),
  ('estrella', 'yáa'),
  ('blanco', 'pūju'),
  ('violeta', 'tuntuutaku'),
  ('negro', 'mukūsa'),
  ('azul', 'kínkia'),
  ('gris claro', 'yunkuim'),
  ('rojo', 'kapaku'),
  ('café', 'ukusmakma'),
  ('celeste', 'sechatin'),
  ('verde', 'samēk'),
  ('café gris', 'pūshu'),
  ('café claro', 'samektaku'),
  ('amarillo', 'yumkumā'),
  ('uno', 'chikíchik'),
  ('dos', 'jímior'),
  ('tres', 'menaint'),
  ('cuatro', 'aíntiuk'),
  ('cinco', 'swěj'),
  ('seis', 'ujúk'),
  ('siete', 'tsénkent'),
  ('ocho', 'yarūsh'),
  ('nueve', 'usúmtai'),
  ('diez', 'náwe'),
  ('cien', 'washím'),
  ('millón', 'amúchar'),
  ('planta medicinal', 'sésa'),
  ('tabaco', 'tsánk'),
  ('achiote', 'ipiák'),
  ('guanto', 'maíklua'),
  ('ayahuasca', 'natem'),
  ('orito', 'tsuákmajech'),
  ('ají', 'jímla'),
  ('caña dulce pequeña', 'nusé padf'),
  ('palmera', 'áchu'),
  ('palmito', 'palmito'),
  ('chonta', 'uwí'),
  ('palmera silvestre', 'terént'),
  ('palmera', 'kuúnt'),
  ('zapallo', 'yuwí'),
  ('zanahoria', 'máya'),
  ('papa', 'papachinia'),
  ('plátano verde', 'pantam'),
  ('camote', 'inchi'),
  ('palma', 'sánku'),
  ('tuyo', 'kénke'),
  ('oro', 'mejéch'),
  ('zanahoria shuar', 'chíki'),
  ('yuca', 'mama'),
  ('uvilla', 'shuinia'),
  ('azulejo', 'suich'),
  ('ganso', 'suingoatu');

select * from usuario
select * from traduccion
-- 215 palabras